#!/usr/bin/env python3
"""
Turn an Encompass users export (xlsx or csv with name / email / phone
columns) into SQL that upserts the sign-in allow list.

    python3 supabase/import_allowed_users.py ~/Downloads/encompass_users.xlsx
    python3 supabase/import_allowed_users.py users.csv --manager gavin@x.com --manager chris@x.com
    python3 supabase/import_allowed_users.py users.xlsx --out supabase/data/allowed_users.sql

Writes supabase/data/allowed_users.sql by default (that folder is
git-ignored: the repo is public and this file holds personal emails and
phone numbers). Paste the file's contents into Supabase -> SQL Editor
and run it. Rows already in the table are updated (name / phone /
role), nothing is deleted.

Columns are found by header, case-insensitively: anything containing
"email" is the email; "phone" / "mobile" / "cell" the phone; "name"
(or First + Last) the name. Rows with no usable email are listed at the
end and skipped.
"""
import argparse
import csv
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")


def read_rows(path):
    ext = os.path.splitext(path)[1].lower()
    if ext in (".xlsx", ".xlsm"):
        try:
            import openpyxl
        except ImportError:
            sys.exit("pip install openpyxl (or export the sheet as CSV first)")
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        ws = wb[wb.sheetnames[0]]
        rows = [[("" if c is None else str(c)).strip() for c in r] for r in ws.iter_rows(values_only=True)]
    else:
        with open(path, newline="", encoding="utf-8-sig") as f:
            rows = [[c.strip() for c in r] for r in csv.reader(f)]
    rows = [r for r in rows if any(r)]
    if not rows:
        sys.exit("no rows in " + path)
    return rows[0], rows[1:]


def find(header, *needles):
    low = [h.lower() for h in header]
    for n in needles:
        for i, h in enumerate(low):
            if n in h:
                return i
    return None


def sql_str(s):
    return "'" + s.replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("file")
    ap.add_argument("--out", default=os.path.join(HERE, "data", "allowed_users.sql"))
    ap.add_argument("--manager", action="append", default=[], help="email to mark as manager (repeatable)")
    ap.add_argument("--default-role", default="rep", choices=["rep", "manager"])
    a = ap.parse_args()

    header, body = read_rows(a.file)
    i_email = find(header, "email", "e-mail")
    if i_email is None:
        sys.exit("no email column in header: " + ", ".join(header))
    i_phone = find(header, "phone", "mobile", "cell")
    i_name = find(header, "full name", "name")
    i_first = find(header, "first")
    i_last = find(header, "last")
    if i_name is not None and (i_name == i_first or i_name == i_last):
        i_name = None

    managers = {m.strip().lower() for m in a.manager}
    seen, out, skipped = {}, [], []
    for r in body:
        def cell(i):
            return r[i] if i is not None and i < len(r) else ""
        email = cell(i_email).strip().lower()
        if not EMAIL_RE.match(email):
            skipped.append(" | ".join(x for x in r if x))
            continue
        name = cell(i_name) or " ".join(x for x in (cell(i_first), cell(i_last)) if x)
        phone = re.sub(r"[^\d+x]", "", cell(i_phone)) if i_phone is not None else ""
        role = "manager" if email in managers else a.default_role
        seen[email] = (name.strip(), phone, role)

    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("-- generated by supabase/import_allowed_users.py from %s\n" % os.path.basename(a.file))
        f.write("insert into public.allowed_users (email, name, phone, role) values\n")
        vals = []
        for email, (name, phone, role) in sorted(seen.items()):
            vals.append("  (%s, %s, %s, %s)" % (
                sql_str(email), sql_str(name) if name else "null",
                sql_str(phone) if phone else "null", sql_str(role)))
        f.write(",\n".join(vals))
        f.write("\non conflict (email) do update set\n"
                "  name = coalesce(excluded.name, allowed_users.name),\n"
                "  phone = coalesce(excluded.phone, allowed_users.phone),\n"
                "  role = excluded.role;\n")

    print("%d people -> %s" % (len(seen), a.out))
    print("managers: %s" % (", ".join(sorted(e for e, v in seen.items() if v[2] == "manager")) or "none"))
    missing = managers - set(seen)
    if missing:
        print("WARNING --manager emails not in the file: " + ", ".join(sorted(missing)))
    if skipped:
        print("skipped %d rows with no usable email:" % len(skipped))
        for s in skipped[:20]:
            print("  " + s)


if __name__ == "__main__":
    main()
