-- GENERATED by tools/program_seed.py from the Fusion supplier list -- REVIEW BEFORE RUNNING.
-- Sets allowed_users.program_brands (the suppliers a brand manager may build programs for)
-- by NAME KEY match against the allow list. Nobody is added to the allow list; no emails here.
-- A brand manager not on the allow list is skipped. Run after 20261008120000_manage_programs.sql.
begin;
update public.allowed_users set program_brands = array['Red Bull']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Chris McCrohan');
update public.allowed_users set program_brands = array['2 Towns Ciderhouse', 'Bell''s', 'Boston Beer Company', 'Brewt''s LLC', 'Buzbee''s Beverages USA LLC', 'Cavalier Ventures, LLC', 'Crook & Marker', 'Forged Irish Stout', 'Hornell Brewing Company', 'Kimo Spirits', 'Laird & Company', 'Montauk Brewing Co', 'New Belgium Brewing Company', 'Park Street Imports', 'Passion Tree Co', 'SN Food & Beverage LLC', 'Saratoga', 'Talkhouse Encore', 'Viva Beverages Inc']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Chris Politano');
update public.allowed_users set program_brands = array['Athletic Brewing Company', 'Efes', 'FIFCO', 'Global Village Imp.', 'MolsonCoors Beverage Company', 'Narragansett', 'Total Beverage Solutions']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Dan Downing');
update public.allowed_users set program_brands = array['Food & Bev Enterprise LLC', 'Vinaio Imports LTD']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Denise Montes');
update public.allowed_users set program_brands = array['1925 Spirits LLC', 'Alte Beverage', 'Bardstown Bourbon Co', 'Bella Ray Beverage', 'Blaze Life LLC', 'Caravella Inc', 'Chateau Diana Winery', 'Cooper Spirits', 'Crescent Canna', 'Cruz Beverage', 'Dad Grass', 'Delta Beverage LLC', 'Dreamz Invenstments LLC', 'Eleven20', 'Emergent Beverage Partners', 'Jerzey Jungle LLC', 'Licores Artesanales', 'Little Water Distillery', 'Lo Secco LLC', 'Lodo Brands', 'Modern Infusions', 'Molly''s', 'OVO Vodka LLC', 'Oceano', 'Paradisse Spirits LLC', 'Pio Imports', 'Power Distribution LLC', 'Prestige', 'Pride & Clarke', 'Primos Imports LLC', 'Radix Labs', 'Riviera Imports', 'SPYRT Worldwide', 'Savorian INC', 'Seafarer', 'Surface Brands', 'The Old G LLC', 'Tilray Alternative Beverage', 'Travelers Club', 'Waterloo Gin']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Jason Koo');
update public.allowed_users set program_brands = array['DG Yuengling Inc', 'Gambrinus Imports', 'Global Beer', 'Heineken USA', 'Lagunitas Brewing Co', 'Pampa Beverages', 'Paulaner']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Perry Calderone');
update public.allowed_users set program_brands = array['Alias Brew Works', 'BJ''S Private Label Brew', 'Barn Brew Co', 'Bold Rock Hard Cider', 'Cape May', 'Cricket Hill', 'Defiant Brewing Co.', 'Duclaw Brewing', 'Evil Genius', 'Flying Fish', 'Garage Beer', 'Industrial Arts Brewing Co', 'Ithaca', 'Long Trail', 'Newburgh Brewing', 'Other Half Brewing Co', 'Popsicle', 'Right Coast Brewing Co', 'River Horse Brewing Co', 'Sapporo', 'Sixpoint Brewing', 'Source Brewing', 'Southern Tier Brewing Company', 'Southern Tier Distilling Company', 'Stone Brewing', 'Tilray Brands', 'Unibroue', 'Victory Brewing Company']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Sean Donahue');
update public.allowed_users set program_brands = array['Artisanal Imports', 'Beak & Skiff', 'Cerveceria La Tropical', 'Constellation Brands', 'HOP WTR', 'Mark Anthony', 'Noca Beverages', 'Phusion Projects', 'Point Brewing', 'US Beverage', 'Vermont Hard Cider', 'XYZ Beverage']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Steve Halloran');
update public.allowed_users set program_brands = array['American Fruits', 'Citizen Cider', 'FX Matt', 'Famosa', 'Great Lakes', 'Harpoon Brewery', 'Hofbrauhaus USA', 'Pabst Brewing Company', 'Radeberger USA', 'Sierra Nevada Brewing Company', 'Warwick Valley']
  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key('Tom Gibbons');
commit;
