#!/usr/bin/env python3
"""Turn Encompass' "Customers" export into SQL for the private account_contacts table.

  python3 tools/load_contacts.py <Customers_export.csv>

Writes supabase/data/account_contacts.sql (git-ignored: the repo is PUBLIC, so
contact names / phones / emails never enter a committed file). Paste that file
into the Supabase SQL Editor; it replaces the whole table in one transaction,
so a refresh is: new export -> run this -> paste -> run.

Contact names are tidied for display: proper case (Mc / O' / D' / hyphens),
"_12" duplicate suffixes, phone numbers, account codes, extensions,
(notes) and stray symbols removed, " / " between two people, "None" and email
addresses typed into the name box dropped (the email moves to Email when that
column is empty). Phones become (973) 555-1234, emails lower case.
"""
import csv, os, re, sys

EMAIL = re.compile(r'^[^@\s]+@[^@\s]+\.[a-z]{2,}$', re.I)
SMALL = {'or', 'and', 'y', 'the'}

def _tok(w):
    if w.lower() in SMALL: return w.lower()
    def part(p):
        if not p: return p
        if '.' in p and len(p) <= 4 and p.replace('.', '').isalpha(): return p.upper()   # initials
        q = p[:1].upper() + p[1:].lower()
        q = re.sub(r"^([OD]')([a-z])", lambda m: m.group(1) + m.group(2).upper(), q)
        q = re.sub(r"^(Mc)([a-z]{3,})", lambda m: 'Mc' + m.group(2)[0].upper() + m.group(2)[1:], q)
        return q
    return '-'.join(part(p) for p in w.split('-'))

def clean_name(raw):
    s = (raw or '').strip()
    if not s or EMAIL.match(s): return ''
    s = re.sub(r'_\d*', '', s)                                   # Joe_17 -> Joe
    s = re.sub(r'\([^)]*\)?', '', s)                             # (notes), (Ext.101), (P)
    s = re.sub(r'\s*(->|[\\/>])\s*', ' / ', s)                   # two people
    s = re.sub(r'\+?\d[\d\s().\-]{6,}\d(\s*/\s*\d+)?', '', s)    # phone numbers
    s = re.sub(r'\b(ext|x)\.?\s*-?\s*\d+\b', '', s, flags=re.I)  # ext 101, X253
    s = re.sub(r'(?<![A-Za-z])[A-Za-z]?\d{2,}\b', '', s)         # account codes
    s = re.sub(r'\b\w*\d\w*\b', '', s)
    s = re.sub(r'\bcell\b|\bnew owner\b', '', s, flags=re.I)
    s = re.sub(r'[^\w\s\'&./\-À-ž]', ' ', s)                     # any other symbol
    s = re.sub(r"''+", "'", s)
    s = re.sub(r'\s+', ' ', s).strip(' /-&')
    s = s if re.search(r'\b[A-Za-z]\.$', s) else s.rstrip('.')
    s = re.sub(r'^(or|and)\s+|\s+(or|and)$', '', s, flags=re.I)
    if not s or s.lower() == 'none': return ''
    s = ' '.join(_tok(w) if w != '/' else '/' for w in s.split(' '))
    return s[:1].upper() + s[1:]

def clean_phone(p):
    d = re.sub(r'\D', '', p or '')
    if len(d) == 11 and d[0] == '1': d = d[1:]
    return f'({d[:3]}) {d[3:6]}-{d[6:]}' if len(d) == 10 else (p or '').strip()

def q(v):
    return 'null' if not v else "'" + v.replace("'", "''") + "'"

def main(src):
    rows = list(csv.DictReader(open(src, encoding='utf-8-sig')))
    out, seen = [], set()
    for r in rows:
        n = (r.get('Customer ID') or '').strip()
        if not n or n in seen: continue
        seen.add(n)
        raw = r.get('Primary Contact') or ''
        email = (r.get('Email') or '').strip().lower()
        if EMAIL.match(raw.strip()) and not email: email = raw.strip().lower()
        name, phone = clean_name(raw), clean_phone(r.get('Phone'))
        if not (name or phone or email): continue
        out.append((n, name, phone, email))
    dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'supabase', 'data')
    os.makedirs(dest, exist_ok=True)
    path = os.path.join(dest, 'account_contacts.sql')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('-- generated by tools/load_contacts.py; contains customer contacts -- do NOT commit\n')
        f.write('begin;\ndelete from public.account_contacts;\n')
        f.write('insert into public.account_contacts (customer_num, contact_name, phone, email) values\n')
        f.write(',\n'.join(f'({q(n)}, {q(a)}, {q(b)}, {q(c)})' for n, a, b, c in out))
        f.write(';\ncommit;\n')
    print(f'{len(out)} of {len(rows)} customers -> {os.path.normpath(path)}')

if __name__ == '__main__':
    if len(sys.argv) != 2: sys.exit(__doc__)
    main(sys.argv[1])
