#!/usr/bin/env python3
"""Seed SQL for Manage Programs (2026-10-08). Writes two files for Gavin to
paste into the Supabase SQL Editor AFTER supabase/migrations/20261008120000_manage_programs.sql:

  supabase/seed/product_master.sql
      public.product_master = every product of the Rolling Distribution
      master (product # / name / supplier / family / package / draft). No
      customer data. The server uses it to check that a brand manager's
      products really belong to their suppliers. Re-run after a product
      refresh.

  supabase/seed/program_brands.sql   (REVIEW BEFORE RUNNING)
      allowed_users.program_brands for the brand managers in the Fusion
      supplier list (rolling-distribution/data/master/suppliers.csv): one
      UPDATE per brand manager, matched by NAME KEY against allowed_users.
      It names nobody who is not already on the allow list, and it writes
      no emails. A manager not listed there gets NO brands (they can still
      create programs for their team). Edit the lists before running if
      the supplier assignments have moved.

  python3 tools/program_seed.py
"""
import csv, json, re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MASTER = ROOT / 'rolling-distribution' / 'data' / 'master'
SEED = ROOT / 'supabase' / 'seed'
DRAFT_RE = re.compile(r'\b(keg|gal)\b', re.I)


def q(s):
    return "'" + str(s or '').replace("'", "''") + "'"


def main():
    SEED.mkdir(parents=True, exist_ok=True)
    products = list(csv.DictReader(open(MASTER / 'products.csv', newline='')))
    out = ['-- GENERATED by tools/program_seed.py -- do not edit. Paste into the Supabase SQL Editor',
           '-- after migration 20261008120000_manage_programs.sql. Safe to run more than once.',
           '-- Products only (no customer data). Re-run after a product refresh.',
           'begin;', 'create temp table _p (product_num text, name text, supplier text, family text, package text, draft boolean) on commit drop;',
           'insert into _p (product_num, name, supplier, family, package, draft) values']
    rows = []
    for p in sorted(products, key=lambda r: r['product_num']):
        draft = bool(DRAFT_RE.search((p.get('package') or '') + ' ' + (p.get('name') or '')))
        rows.append('  (%s, %s, %s, %s, %s, %s)' % (q(p['product_num']), q(p['name']), q(p.get('supplier')), q(p.get('family')), q(p.get('package')), 'true' if draft else 'false'))
    out.append(',\n'.join(rows) + ';')
    out += ['insert into public.product_master (product_num, name, supplier, family, package, draft)',
            '  select product_num, name, supplier, family, package, draft from _p',
            '  on conflict (product_num) do update set name = excluded.name, supplier = excluded.supplier, family = excluded.family,',
            '    package = excluded.package, draft = excluded.draft, updated_at = now();',
            'delete from public.product_master where product_num not in (select product_num from _p);',
            'commit;', '']
    (SEED / 'product_master.sql').write_text('\n'.join(out))

    bm = defaultdict(list)
    for r in csv.DictReader(open(MASTER / 'suppliers.csv', newline='')):
        name = (r.get('brand_manager') or '').strip()
        if name and r.get('supplier'):
            bm[name].append(r['supplier'].strip())
    out = ['-- GENERATED by tools/program_seed.py from the Fusion supplier list -- REVIEW BEFORE RUNNING.',
           '-- Sets allowed_users.program_brands (the suppliers a brand manager may build programs for)',
           '-- by NAME KEY match against the allow list. Nobody is added to the allow list; no emails here.',
           '-- A brand manager not on the allow list is skipped. Run after 20261008120000_manage_programs.sql.',
           'begin;']
    for name, sups in sorted(bm.items()):
        out.append('update public.allowed_users set program_brands = array[%s]' % ', '.join(q(s) for s in sorted(set(sups))))
        out.append("  where role = 'manager' and public.kdh_name_key(name) = public.kdh_name_key(%s);" % q(name))
    out += ['commit;', '']
    (SEED / 'program_brands.sql').write_text('\n'.join(out))
    print('wrote product_master.sql (%d products) and program_brands.sql (%d brand managers)' % (len(rows), len(bm)))


if __name__ == '__main__':
    main()
