-- MANAGE PROGRAMS (2026-10-08). Run AFTER 20261005090000_photo_admin.sql.
-- Idempotent: safe to run more than once.
--
-- Managers create incentives and MPOs through a guided workflow in the Hub
-- (/manage-programs/). Every program is a row in public.programs with one or
-- more VERSIONS of its definition (program_versions.definition, jsonb). The
-- approver -- the one allow-list row with program_admin = true (Gavin) --
-- approves or returns each submitted version; only an approved version is
-- ever shown to participants. Manager-only financial terms live in a
-- SEPARATE table (program_finance) that participants can never select from,
-- so no dollar amount can reach a rep through any query, export or notice.
--
-- WHO may do what is decided HERE, in security-definer functions, never on
-- the page:
--   program_admin (Gavin)      everything: create, edit any, approve, return,
--                              close out. Identified by the flag on his
--                              allow-list row, NOT by name.
--   any manager                create drafts, edit / submit their own drafts.
--   brand manager              a manager with program_brands set: may put ANY
--                              rep in a program, but only products of those
--                              suppliers.
--   district manager           a manager whom reps report to (allowed_users.
--                              reports_to chain): may put only their team in.
--   neither                    may save drafts, but cannot SUBMIT a program
--                              that names participants or products (a missing
--                              assignment never widens access).
--   reps / associates          read only the approved, non-test programs they
--                              are listed in, with no financial terms.
--
-- WHO is the admin / which suppliers a brand manager owns is NOT written here
-- (the repo is public). After running this file, in the SQL Editor:
--   update public.allowed_users set program_admin = true where email = '<gavin>';
--   update public.allowed_users set program_brands = array['Constellation','Lagunitas Brewing Co']
--     where email = '<brand manager>';
-- supabase/seed/program_brands.sql (generated by tools/program_seed.py from the
-- Fusion supplier list) sets program_brands by NAME match -- review it first.
--
-- Product master: supabase/seed/product_master.sql (generated by
-- tools/program_seed.py; product # / name / supplier / family / package only,
-- no customer data) lets the server check that a brand manager's products
-- really belong to their suppliers. Until it is loaded, a brand-limited
-- manager cannot submit (nothing to check against), an unlimited one can.

-- ------------------------------------------------------------ roles
alter table public.allowed_users add column if not exists program_admin boolean not null default false;
alter table public.allowed_users add column if not exists program_brands text[];
comment on column public.allowed_users.program_admin is
  'Approves every program (Gavin). Set only in the SQL Editor / Table Editor.';
comment on column public.allowed_users.program_brands is
  'Brand manager: the suppliers this manager may build programs for. NULL = not a brand manager.';

create or replace function public.kdh_is_program_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select program_admin from public.allowed_users where email = public.kdh_caller_email()), false);
$$;
revoke all on function public.kdh_is_program_admin() from public;
grant execute on function public.kdh_is_program_admin() to authenticated;

-- the reps / associates who roll up to a name through allowed_users.reports_to
-- (rep -> DM -> VP ...). Names, because that is what reports_to holds.
create or replace function public.kdh_reports_under(p_name text)
returns setof text language sql stable security definer set search_path = public as $$
  with recursive t as (
    select u.name from public.allowed_users u
      where u.reports_to is not null and lower(trim(u.reports_to)) = lower(trim(p_name))
    union
    select u.name from public.allowed_users u join t on lower(trim(u.reports_to)) = lower(trim(t.name))
  )
  select name from t where name is not null;
$$;
revoke all on function public.kdh_reports_under(text) from public;

-- The caller's program scope. team: null = any participant, [] = none;
-- brands: null = any supplier, [] = none. A manager with neither a team nor
-- brands may draft but not submit anything with participants or products.
create or replace function public.kdh_program_scope()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  me record; team text[]; brands text[];
begin
  select * into me from public.allowed_users where email = public.kdh_caller_email();
  if me is null or me.role <> 'manager' then
    return jsonb_build_object('manager', false, 'admin', false, 'team', '[]'::jsonb, 'brands', '[]'::jsonb);
  end if;
  if me.program_admin then
    return jsonb_build_object('manager', true, 'admin', true, 'team', null, 'brands', null, 'name', me.name);
  end if;
  select array_agg(n) into team from public.kdh_reports_under(me.name) n;
  brands := me.program_brands;
  return jsonb_build_object(
    'manager', true, 'admin', false, 'name', me.name,
    'team',   case when team is null and brands is not null then null            -- brand manager: any rep
                   when team is null then '[]'::jsonb else to_jsonb(team) end,
    'brands', case when brands is null and team is not null then null            -- district manager: any supplier
                   when brands is null then '[]'::jsonb else to_jsonb(brands) end);
end $$;
revoke all on function public.kdh_program_scope() from public;
grant execute on function public.kdh_program_scope() to authenticated;

-- everyone a manager may pick from: name, kind (rep / associate / manager),
-- title, reports_to. No emails. Associates = allow-list rows whose Encompass
-- title says so; there is NO associate -> account mapping on the site yet.
create or replace function public.kdh_program_people()
returns table (name text, kind text, title text, reports_to text)
language sql stable security definer set search_path = public as $$
  select u.name,
         case when u.role = 'rep' then 'rep'
              when u.title ~* 'associate|merchandis' then 'associate'
              else 'manager' end,
         u.title, u.reports_to
  from public.allowed_users u
  where public.kdh_is_manager() and u.name is not null
  order by u.name;
$$;
revoke all on function public.kdh_program_people() from public;
grant execute on function public.kdh_program_people() to authenticated;

-- ------------------------------------------------------------ product master (seeded; no customer data)
create table if not exists public.product_master (
  product_num text primary key,
  name        text not null,
  supplier    text,
  family      text,
  package     text,
  size        text,
  draft       boolean not null default false,
  updated_at  timestamptz not null default now()
);
alter table public.product_master enable row level security;
drop policy if exists "signed in read products" on public.product_master;
create policy "signed in read products" on public.product_master for select to authenticated using (true);
grant select on public.product_master to authenticated;

-- ------------------------------------------------------------ programs
create table if not exists public.programs (
  id               uuid primary key default gen_random_uuid(),
  kind             text not null check (kind in ('incentive', 'mpo')),
  is_test          boolean not null default false,
  title            text not null,
  audience         text[] not null default '{rep}',
  supplier         text,
  start_date       date,
  end_date         date,
  status           text not null default 'draft'
                   check (status in ('draft', 'submitted', 'returned', 'approved', 'closed', 'archived')),
  approved_version int,
  owner_email      text not null,
  owner_name       text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists programs_status on public.programs (status, end_date);

create table if not exists public.program_versions (
  id            uuid primary key default gen_random_uuid(),
  program_id    uuid not null references public.programs(id) on delete cascade,
  version       int not null,
  definition    jsonb not null,
  status        text not null default 'draft'
                check (status in ('draft', 'submitted', 'returned', 'approved', 'superseded', 'withdrawn')),
  recalc        text check (recalc is null or recalc in ('retroactive', 'future')),
  change_note   text,
  submitted_by  text, submitted_at timestamptz,
  reviewed_by   text, reviewed_at  timestamptz, review_note text,
  created_by    text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (program_id, version)
);

-- manager-only money. Participants have no path to this table.
create table if not exists public.program_finance (
  version_id  uuid primary key references public.program_versions(id) on delete cascade,
  terms       jsonb not null default '{}'::jsonb,
  updated_by  text,
  updated_at  timestamptz not null default now()
);

create table if not exists public.program_events (
  id          bigint generated always as identity primary key,
  program_id  uuid not null references public.programs(id) on delete cascade,
  version     int,
  actor_email text not null,
  actor_name  text,
  action      text not null,
  detail      jsonb,
  at          timestamptz not null default now()
);
create index if not exists program_events_prog on public.program_events (program_id, at desc);

create table if not exists public.program_templates (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  definition  jsonb not null,
  owner_email text not null,
  owner_name  text,
  created_at  timestamptz not null default now()
);

-- a notice to participants after an approved version takes effect
create table if not exists public.program_notices (
  id           uuid primary key default gen_random_uuid(),
  program_id   uuid not null references public.programs(id) on delete cascade,
  version      int not null,
  kind         text not null check (kind in ('new', 'updated', 'ended', 'extended')),
  summary      text not null,
  participants text[] not null default '{}',   -- name keys (kdh_name_key)
  is_test      boolean not null default false,
  created_at   timestamptz not null default now()
);
create table if not exists public.program_notice_reads (
  notice_id uuid not null references public.program_notices(id) on delete cascade,
  email     text not null,
  read_at   timestamptz not null default now(),
  primary key (notice_id, email)
);

create table if not exists public.program_closeouts (
  program_id   uuid primary key references public.programs(id) on delete cascade,
  version      int not null,
  data_through date,
  result       jsonb,
  note         text,
  locked_by    text not null,
  locked_at    timestamptz not null default now()
);

-- ------------------------------------------------------------ row-level security
alter table public.programs            enable row level security;
alter table public.program_versions    enable row level security;
alter table public.program_finance     enable row level security;
alter table public.program_events      enable row level security;
alter table public.program_templates   enable row level security;
alter table public.program_notices     enable row level security;
alter table public.program_notice_reads enable row level security;
alter table public.program_closeouts   enable row level security;

-- managers read everything about programs (lists, versions, history, money).
-- Reps and associates read NOTHING directly: they get their programs through
-- kdh_my_programs() below, which returns the approved definition only.
drop policy if exists "managers read programs" on public.programs;
create policy "managers read programs" on public.programs for select to authenticated using (public.kdh_is_manager());
drop policy if exists "managers read versions" on public.program_versions;
create policy "managers read versions" on public.program_versions for select to authenticated using (public.kdh_is_manager());
drop policy if exists "managers read finance" on public.program_finance;
create policy "managers read finance" on public.program_finance for select to authenticated using (public.kdh_is_manager());
drop policy if exists "managers read events" on public.program_events;
create policy "managers read events" on public.program_events for select to authenticated using (public.kdh_is_manager());
drop policy if exists "managers read closeouts" on public.program_closeouts;
create policy "managers read closeouts" on public.program_closeouts for select to authenticated using (public.kdh_is_manager());
drop policy if exists "managers read templates" on public.program_templates;
create policy "managers read templates" on public.program_templates for select to authenticated using (public.kdh_is_manager());
drop policy if exists "managers add templates" on public.program_templates;
create policy "managers add templates" on public.program_templates for insert to authenticated
  with check (public.kdh_is_manager() and owner_email = public.kdh_caller_email());
drop policy if exists "owner removes template" on public.program_templates;
create policy "owner removes template" on public.program_templates for delete to authenticated
  using (owner_email = public.kdh_caller_email() or public.kdh_is_program_admin());
drop policy if exists "managers read notices" on public.program_notices;
create policy "managers read notices" on public.program_notices for select to authenticated using (public.kdh_is_manager());
drop policy if exists "own reads" on public.program_notice_reads;
create policy "own reads" on public.program_notice_reads for select to authenticated using (email = public.kdh_caller_email());
drop policy if exists "mark own read" on public.program_notice_reads;
create policy "mark own read" on public.program_notice_reads for insert to authenticated with check (email = public.kdh_caller_email());

grant select on public.programs, public.program_versions, public.program_finance, public.program_events,
                public.program_closeouts, public.program_notices, public.program_notice_reads to authenticated;
grant select, insert, delete on public.program_templates to authenticated;
grant insert on public.program_notice_reads to authenticated;

-- every write to programs / versions / finance / events / closeouts goes through
-- the functions below (security definer); nothing is granted directly.

-- ------------------------------------------------------------ helpers
create or replace function public.kdh_program_touch()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;
drop trigger if exists programs_touch on public.programs;
create trigger programs_touch before update on public.programs for each row execute function public.kdh_program_touch();
drop trigger if exists program_versions_touch on public.program_versions;
create trigger program_versions_touch before update on public.program_versions for each row execute function public.kdh_program_touch();

create or replace function public.kdh_program_log(p_program uuid, p_version int, p_action text, p_detail jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare me text := public.kdh_caller_email();
begin
  insert into public.program_events (program_id, version, actor_email, actor_name, action, detail)
  values (p_program, p_version, me, (select name from public.allowed_users where email = me), p_action, p_detail);
end $$;
revoke all on function public.kdh_program_log(uuid, int, text, jsonb) from public;

-- Participants named in a definition, as name KEYS (what the middleware and
-- the per-rep data files use). definition.participants.resolved = {reps:[names], associates:[names]}.
create or replace function public.kdh_program_participant_keys(def jsonb)
returns text[] language sql immutable as $$
  select coalesce(array_agg(distinct public.kdh_name_key(x)), '{}')
  from (
    select jsonb_array_elements_text(coalesce(def #> '{participants,resolved,reps}', '[]'::jsonb)) x
    union all
    select jsonb_array_elements_text(coalesce(def #> '{participants,resolved,associates}', '[]'::jsonb)) x
  ) s where x <> '';
$$;

-- Is this definition inside the caller's scope? Returns null when it is,
-- else the reason. The admin is never limited.
create or replace function public.kdh_program_scope_problem(def jsonb)
returns text language plpgsql stable security definer set search_path = public as $$
declare
  sc jsonb := public.kdh_program_scope();
  team text[]; brands text[]; names text[]; bad text[]; pids text[]; n int;
begin
  if (sc->>'admin')::boolean then return null; end if;
  if not (sc->>'manager')::boolean then return 'Only a manager can build programs.'; end if;
  select array_agg(x) into names from (
    select jsonb_array_elements_text(coalesce(def #> '{participants,resolved,reps}', '[]'::jsonb)) x
    union all
    select jsonb_array_elements_text(coalesce(def #> '{participants,resolved,associates}', '[]'::jsonb)) x) s;
  if names is not null and array_length(names, 1) > 0 and sc->'team' <> 'null'::jsonb then
    select array_agg(x) into team from jsonb_array_elements_text(sc->'team') x;
    select array_agg(x) into bad from unnest(names) x
      where not exists (select 1 from unnest(coalesce(team, '{}')) t where public.kdh_name_key(t) = public.kdh_name_key(x));
    if bad is not null then
      return case when coalesce(array_length(team, 1), 0) = 0
        then 'You have no team or brand assignment on file, so you cannot submit a program with participants. Ask Gavin to set it.'
        else 'Not on your team: ' || array_to_string(bad, ', ') end;
    end if;
  end if;
  select array_agg(p->>'id') into pids from jsonb_array_elements(coalesce(def #> '{products,resolved}', '[]'::jsonb)) p;
  if pids is not null and array_length(pids, 1) > 0 and sc->'brands' <> 'null'::jsonb then
    select array_agg(x) into brands from jsonb_array_elements_text(sc->'brands') x;
    if coalesce(array_length(brands, 1), 0) = 0 then
      return 'You have no brand or team assignment on file, so you cannot submit a program with products. Ask Gavin to set it.';
    end if;
    select count(*) into n from public.product_master;
    if n = 0 then return 'The product master is not loaded yet, so brand scope cannot be checked. Ask Gavin to load supabase/seed/product_master.sql.'; end if;
    select array_agg(distinct coalesce(m.supplier, '(unknown)')) into bad
      from unnest(pids) id left join public.product_master m on m.product_num = id
      where m.product_num is null or not (lower(coalesce(m.supplier, '')) = any (select lower(b) from unnest(brands) b));
    if bad is not null then return 'Outside your brands: ' || array_to_string(bad, ', '); end if;
  end if;
  return null;
end $$;
revoke all on function public.kdh_program_scope_problem(jsonb) from public;
grant execute on function public.kdh_program_scope_problem(jsonb) to authenticated;

-- a manager may edit a program when they own it, are the admin, or the
-- program sits entirely inside their scope
create or replace function public.kdh_program_can_edit(p_program uuid)
returns boolean language plpgsql stable security definer set search_path = public as $$
declare pr record; v jsonb;
begin
  select * into pr from public.programs where id = p_program;
  if pr is null then return false; end if;
  if public.kdh_is_program_admin() then return true; end if;
  if not public.kdh_is_manager() then return false; end if;
  if pr.owner_email = public.kdh_caller_email() then return true; end if;
  select definition into v from public.program_versions where program_id = p_program order by version desc limit 1;
  return v is not null and public.kdh_program_scope_problem(v) is null
     and (select coalesce(jsonb_array_length(v #> '{participants,resolved,reps}'), 0)
            + coalesce(jsonb_array_length(v #> '{participants,resolved,associates}'), 0)) > 0;
end $$;
revoke all on function public.kdh_program_can_edit(uuid) from public;
grant execute on function public.kdh_program_can_edit(uuid) to authenticated;

-- keys a definition must never carry (money lives in program_finance)
create or replace function public.kdh_program_strip_money(def jsonb)
returns jsonb language sql immutable as $$
  select (def - 'finance' - 'payout' - 'payouts' - 'rates' - 'billback' - 'dollars');
$$;

-- ------------------------------------------------------------ save a draft
-- p = {id?, definition, finance?, note?}. Creates the program on the first
-- save; afterwards rewrites the current draft / returned version. An approved
-- program gets a NEW draft version (a revision) -- the approved one stays
-- live until Gavin approves the revision.
create or replace function public.kdh_program_save(p jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me text := public.kdh_caller_email();
  myname text := (select name from public.allowed_users where email = public.kdh_caller_email());
  def jsonb := public.kdh_program_strip_money(coalesce(p->'definition', '{}'::jsonb));
  pid uuid := nullif(p->>'id', '')::uuid;
  pr record; ver record; vno int; vid uuid; st text;
begin
  if not public.kdh_is_manager() then raise exception 'managers only' using errcode = '42501'; end if;
  if coalesce(def->>'title', '') = '' then raise exception 'a title is required'; end if;
  if (def->>'kind') not in ('incentive', 'mpo') then raise exception 'kind must be incentive or mpo'; end if;
  if pid is null then
    insert into public.programs (kind, is_test, title, audience, supplier, start_date, end_date, owner_email, owner_name)
    values (def->>'kind', coalesce((def->>'isTest')::boolean, false), def->>'title',
            coalesce((select array_agg(x) from jsonb_array_elements_text(coalesce(def->'audience', '["rep"]'::jsonb)) x), '{rep}'),
            def->>'supplier', nullif(def #>> '{period,start}', '')::date, nullif(def #>> '{period,end}', '')::date, me, myname)
    returning * into pr;
    pid := pr.id; vno := 1;
    insert into public.program_versions (program_id, version, definition, status, created_by)
    values (pid, 1, def, 'draft', me) returning id into vid;
    perform public.kdh_program_log(pid, 1, 'created', jsonb_build_object('title', def->>'title', 'isTest', pr.is_test));
  else
    select * into pr from public.programs where id = pid;
    if pr is null then raise exception 'no such program'; end if;
    if not public.kdh_program_can_edit(pid) then raise exception 'not yours to edit' using errcode = '42501'; end if;
    if pr.status in ('closed', 'archived') then raise exception 'a closed program cannot be edited'; end if;
    select * into ver from public.program_versions where program_id = pid order by version desc limit 1;
    if ver.status in ('draft', 'returned') then
      update public.program_versions set definition = def, status = 'draft', change_note = coalesce(p->>'note', change_note)
        where id = ver.id;
      vno := ver.version; vid := ver.id;
    elsif ver.status = 'submitted' then
      raise exception 'this version is awaiting approval; withdraw it or wait';
    else   -- approved / superseded: open a revision
      vno := ver.version + 1;
      insert into public.program_versions (program_id, version, definition, status, change_note, created_by)
      values (pid, vno, def, 'draft', p->>'note', me) returning id into vid;
      perform public.kdh_program_log(pid, vno, 'revision_opened', jsonb_build_object('from', ver.version));
    end if;
    -- the list columns follow the newest definition only while nothing is approved
    update public.programs set
      title = case when approved_version is null then def->>'title' else title end,
      is_test = case when approved_version is null then coalesce((def->>'isTest')::boolean, is_test) else is_test end,
      audience = coalesce((select array_agg(x) from jsonb_array_elements_text(coalesce(def->'audience', '[]'::jsonb)) x), audience),
      supplier = coalesce(def->>'supplier', supplier),
      start_date = case when approved_version is null then nullif(def #>> '{period,start}', '')::date else start_date end,
      end_date   = case when approved_version is null then nullif(def #>> '{period,end}', '')::date else end_date end,
      status = case when status in ('returned', 'submitted') then 'draft' else status end
      where id = pid;
    perform public.kdh_program_log(pid, vno, 'saved', null);
  end if;
  if p ? 'finance' then
    insert into public.program_finance (version_id, terms, updated_by) values (vid, coalesce(p->'finance', '{}'::jsonb), me)
      on conflict (version_id) do update set terms = excluded.terms, updated_by = excluded.updated_by, updated_at = now();
  end if;
  return jsonb_build_object('id', pid, 'version', vno, 'versionId', vid);
end $$;
revoke all on function public.kdh_program_save(jsonb) from public;
grant execute on function public.kdh_program_save(jsonb) to authenticated;

-- ------------------------------------------------------------ submit for approval
create or replace function public.kdh_program_submit(p_program uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare me text := public.kdh_caller_email(); ver record; why text; pr record;
begin
  select * into pr from public.programs where id = p_program;
  if pr is null then raise exception 'no such program'; end if;
  if not public.kdh_program_can_edit(p_program) then raise exception 'not yours to submit' using errcode = '42501'; end if;
  select * into ver from public.program_versions where program_id = p_program order by version desc limit 1;
  if ver.status not in ('draft', 'returned') then raise exception 'nothing to submit (version % is %)', ver.version, ver.status; end if;
  why := public.kdh_program_scope_problem(ver.definition);
  if why is not null then raise exception '%', why using errcode = '42501'; end if;
  if coalesce(ver.definition #>> '{period,start}', '') = '' or coalesce(ver.definition #>> '{period,end}', '') = '' then
    raise exception 'start and end dates are required';
  end if;
  if coalesce(jsonb_array_length(ver.definition -> 'objectives'), 0) = 0 then raise exception 'at least one objective is required'; end if;
  update public.program_versions set status = 'submitted', submitted_by = me, submitted_at = now() where id = ver.id;
  update public.programs set status = 'submitted' where id = p_program;
  perform public.kdh_program_log(p_program, ver.version, 'submitted', null);
  return jsonb_build_object('id', p_program, 'version', ver.version, 'status', 'submitted');
end $$;
revoke all on function public.kdh_program_submit(uuid) from public;
grant execute on function public.kdh_program_submit(uuid) to authenticated;

create or replace function public.kdh_program_withdraw(p_program uuid)
returns void language plpgsql security definer set search_path = public as $$
declare ver record;
begin
  if not public.kdh_program_can_edit(p_program) then raise exception 'not yours' using errcode = '42501'; end if;
  select * into ver from public.program_versions where program_id = p_program order by version desc limit 1;
  if ver.status <> 'submitted' then raise exception 'not awaiting approval'; end if;
  update public.program_versions set status = 'draft', submitted_by = null, submitted_at = null where id = ver.id;
  update public.programs set status = case when approved_version is null then 'draft' else status end where id = p_program;
  perform public.kdh_program_log(p_program, ver.version, 'withdrawn', null);
end $$;
revoke all on function public.kdh_program_withdraw(uuid) from public;
grant execute on function public.kdh_program_withdraw(uuid) to authenticated;

-- ------------------------------------------------------------ review (admin only)
-- p = {id, decision:'approve'|'return', note?, recalc?:'retroactive'|'future'}
create or replace function public.kdh_program_review(p jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me text := public.kdh_caller_email();
  pid uuid := (p->>'id')::uuid; ver record; pr record; prev int; keys text[]; kind text;
begin
  if not public.kdh_is_program_admin() then raise exception 'only the program approver can do this' using errcode = '42501'; end if;
  select * into pr from public.programs where id = pid;
  if pr is null then raise exception 'no such program'; end if;
  select * into ver from public.program_versions where program_id = pid order by version desc limit 1;
  if ver.status <> 'submitted' then raise exception 'version % is not awaiting approval', ver.version; end if;
  if p->>'decision' = 'return' then
    update public.program_versions set status = 'returned', reviewed_by = me, reviewed_at = now(), review_note = p->>'note' where id = ver.id;
    update public.programs set status = case when approved_version is null then 'returned' else 'approved' end where id = pid;
    perform public.kdh_program_log(pid, ver.version, 'returned', jsonb_build_object('note', p->>'note'));
    return jsonb_build_object('id', pid, 'version', ver.version, 'status', 'returned');
  end if;
  if p->>'decision' <> 'approve' then raise exception 'decision must be approve or return'; end if;
  prev := pr.approved_version;
  if prev is not null and coalesce(p->>'recalc', '') not in ('retroactive', 'future') then
    raise exception 'a change to a published program needs a recalc choice: retroactive or future';
  end if;
  update public.program_versions set status = 'superseded' where program_id = pid and status = 'approved';
  update public.program_versions set status = 'approved', reviewed_by = me, reviewed_at = now(), review_note = p->>'note',
    recalc = case when prev is null then null else p->>'recalc' end where id = ver.id;
  update public.programs set status = 'approved', approved_version = ver.version,
    title = ver.definition->>'title', is_test = coalesce((ver.definition->>'isTest')::boolean, is_test),
    supplier = ver.definition->>'supplier',
    audience = coalesce((select array_agg(x) from jsonb_array_elements_text(coalesce(ver.definition->'audience', '[]'::jsonb)) x), audience),
    start_date = nullif(ver.definition #>> '{period,start}', '')::date, end_date = nullif(ver.definition #>> '{period,end}', '')::date
    where id = pid;
  keys := public.kdh_program_participant_keys(ver.definition);
  kind := case when prev is null then 'new'
               when (ver.definition #>> '{period,end}')::date > (select nullif(definition #>> '{period,end}', '')::date from public.program_versions where program_id = pid and version = prev) then 'extended'
               else 'updated' end;
  insert into public.program_notices (program_id, version, kind, summary, participants, is_test)
  values (pid, ver.version, kind,
          case when kind = 'new' then 'New program: ' || (ver.definition->>'title')
               when kind = 'extended' then (ver.definition->>'title') || ' was extended' || coalesce(' — ' || ver.change_note, '')
               else (ver.definition->>'title') || ' was updated' || coalesce(' — ' || ver.change_note, '') end,
          keys, coalesce((ver.definition->>'isTest')::boolean, false));
  perform public.kdh_program_log(pid, ver.version, 'approved', jsonb_build_object('recalc', p->>'recalc', 'note', p->>'note', 'previous', prev));
  return jsonb_build_object('id', pid, 'version', ver.version, 'status', 'approved');
end $$;
revoke all on function public.kdh_program_review(jsonb) from public;
grant execute on function public.kdh_program_review(jsonb) to authenticated;

-- ------------------------------------------------------------ duplicate
create or replace function public.kdh_program_duplicate(p_program uuid, p_title text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare def jsonb; fin jsonb; src record; res jsonb;
begin
  if not public.kdh_is_manager() then raise exception 'managers only' using errcode = '42501'; end if;
  select v.definition, f.terms into def, fin from public.program_versions v
    left join public.program_finance f on f.version_id = v.id
    where v.program_id = p_program order by v.version desc limit 1;
  if def is null then raise exception 'no such program'; end if;
  def := def || jsonb_build_object('title', coalesce(nullif(p_title, ''), (def->>'title') || ' (copy)'), 'isTest', true);
  res := public.kdh_program_save(jsonb_build_object('definition', def, 'finance', coalesce(fin, '{}'::jsonb)));
  perform public.kdh_program_log((res->>'id')::uuid, 1, 'duplicated', jsonb_build_object('from', p_program));
  return res;
end $$;
revoke all on function public.kdh_program_duplicate(uuid, text) from public;
grant execute on function public.kdh_program_duplicate(uuid, text) to authenticated;

-- ------------------------------------------------------------ close out (admin only)
-- Locks the approved result. p = {id, dataThrough, result, note}
create or replace function public.kdh_program_closeout(p jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare pid uuid := (p->>'id')::uuid; pr record;
begin
  if not public.kdh_is_program_admin() then raise exception 'only the program approver can close out' using errcode = '42501'; end if;
  select * into pr from public.programs where id = pid;
  if pr is null or pr.approved_version is null then raise exception 'nothing approved to close'; end if;
  if pr.end_date is null or pr.end_date >= current_date then raise exception 'the earning period has not ended'; end if;
  insert into public.program_closeouts (program_id, version, data_through, result, note, locked_by)
  values (pid, pr.approved_version, nullif(p->>'dataThrough', '')::date, p->'result', p->>'note', public.kdh_caller_email())
  on conflict (program_id) do nothing;
  update public.programs set status = 'closed' where id = pid;
  update public.program_versions set status = 'withdrawn' where program_id = pid and status in ('draft', 'returned', 'submitted');
  insert into public.program_notices (program_id, version, kind, summary, participants, is_test)
  select pid, pr.approved_version, 'ended', pr.title || ' is closed out (data through ' || coalesce(p->>'dataThrough', 'n/a') || ')',
         public.kdh_program_participant_keys(v.definition), pr.is_test
  from public.program_versions v where v.program_id = pid and v.version = pr.approved_version;
  perform public.kdh_program_log(pid, pr.approved_version, 'closed', p - 'result' - 'id');
end $$;
revoke all on function public.kdh_program_closeout(jsonb) from public;
grant execute on function public.kdh_program_closeout(jsonb) to authenticated;

create or replace function public.kdh_program_archive(p_program uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.kdh_program_can_edit(p_program) then raise exception 'not yours' using errcode = '42501'; end if;
  if exists (select 1 from public.programs where id = p_program and approved_version is not null) and not public.kdh_is_program_admin() then
    raise exception 'only the program approver can archive a published program' using errcode = '42501';
  end if;
  update public.programs set status = 'archived' where id = p_program;
  update public.program_versions set status = 'withdrawn' where program_id = p_program and status in ('draft', 'returned', 'submitted');
  perform public.kdh_program_log(p_program, null, 'archived', null);
end $$;
revoke all on function public.kdh_program_archive(uuid) from public;
grant execute on function public.kdh_program_archive(uuid) to authenticated;

-- ------------------------------------------------------------ what participants see
-- The approved definition of every program the caller is listed in -- never a
-- test program, never financial terms, never a draft. A manager may ask for a
-- named rep's view (preview); that view DOES include test programs, which is
-- how Gavin checks a test program before anyone else can see it.
create or replace function public.kdh_my_programs(p_rep text default null)
returns table (id uuid, kind text, is_test boolean, version int, approved_at timestamptz, recalc text,
               start_date date, end_date date, status text, definition jsonb)
language plpgsql stable security definer set search_path = public as $$
declare k text; mgr boolean := public.kdh_is_manager();
begin
  if p_rep is not null and p_rep <> '' then
    if not mgr then raise exception 'managers only' using errcode = '42501'; end if;
    k := public.kdh_name_key(p_rep);
  else
    k := public.kdh_my_key();
  end if;
  if coalesce(k, '') = '' then return; end if;
  return query
    select pr.id, pr.kind, pr.is_test, v.version, v.reviewed_at, v.recalc, pr.start_date, pr.end_date, pr.status,
           v.definition
    from public.programs pr
    join public.program_versions v on v.program_id = pr.id and v.version = pr.approved_version
    where pr.status in ('approved', 'closed')
      and (not pr.is_test or (mgr and p_rep is not null))
      and k = any (public.kdh_program_participant_keys(v.definition))
    order by pr.end_date nulls last, pr.title;
end $$;
revoke all on function public.kdh_my_programs(text) from public;
grant execute on function public.kdh_my_programs(text) to authenticated;

-- unread notices for the caller (no money in a notice; test notices only in preview)
create or replace function public.kdh_my_program_notices(p_rep text default null)
returns table (id uuid, program_id uuid, kind text, summary text, created_at timestamptz, is_test boolean)
language plpgsql stable security definer set search_path = public as $$
declare k text; mgr boolean := public.kdh_is_manager();
begin
  if p_rep is not null and p_rep <> '' then
    if not mgr then raise exception 'managers only' using errcode = '42501'; end if;
    k := public.kdh_name_key(p_rep);
  else
    k := public.kdh_my_key();
  end if;
  if coalesce(k, '') = '' then return; end if;
  return query
    select n.id, n.program_id, n.kind, n.summary, n.created_at, n.is_test
    from public.program_notices n
    where k = any (n.participants)
      and (not n.is_test or (mgr and p_rep is not null))
      and n.created_at > now() - interval '45 days'
      and not exists (select 1 from public.program_notice_reads r where r.notice_id = n.id and r.email = public.kdh_caller_email())
    order by n.created_at desc;
end $$;
revoke all on function public.kdh_my_program_notices(text) from public;
grant execute on function public.kdh_my_program_notices(text) to authenticated;
